dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package

before_deploy:
  -sed -i "s/__VERSION__/$TRAVIS_BUILD_NUMBER/g" bintray-descriptor.json
  - cat bintray-descriptor.json

deploy:
  provider: bintray
  skip_cleanup: true
  file: bintray-descriptor.json
  user: psifunction612
  key: $BINTRAY_API_KEY